name: Integration Tests
on:
  schedule:
  - cron: '0 10 * * Sun'
permissions:
  contents: read

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_ENV_HINTS: 1

jobs:
  tests:
    runs-on: macos-latest
    steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
      with:
        core: true
        cask: true
        test-bot: false

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - run: rake test:api-readall-test

    - run: rake test:branch-compare

    - run: rake test:generate-api-diff

    - run: rake test:service-diff
