name: Merge Checks
on:
  push:
    branches: master
  pull_request:
permissions:
  contents: read

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_ENV_HINTS: 1

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
      with:
        core: false
        cask: false
        test-bot: false

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Lint Ruby code
      run: rake lint:check

    - name: Check if readme is outdated
      run: rake readme:outdated

    - name: Check for missing integration tests
      run: rake missing-tests
