name: CI
on:
  push:
    branches: master
  pull_request:
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Cache Homebrew Bundler RubyGems
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.set-up-homebrew.outputs.gems-path }}
        key: ubuntu-latest-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
        restore-keys: ubuntu-latest-rubygems-

    - name: Install Homebrew Bundler RubyGems
      if: steps.cache.outputs.cache-hit != 'true'
      run: brew install-bundler-gems

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - run: rake lint:check

    - run: rake readme:outdated 
